import 'vant/es/picker-group/style/index.mjs'
import 'vant/es/field/style/index.mjs'
import 'vant/es/icon/style/index.mjs'
import 'vant/es/popup/style/index.mjs'
import 'vant/es/date-picker/style/index.mjs'
import 'vant/es/time-picker/style/index.mjs'
import '@hl/theme-chalk/date.scss'
